export { default as AirBnBLogo } from './AirBnBLogo';
export { default as AmazonLogo } from './AmazonLogo';
export { default as BookMyShowLogo } from './BookMyShowLogo';
export { default as GoogleLogo } from './GoogleLogo';
export { default as HubspotLogo } from './HubspotLogo';
export { default as MicrosoftLogo } from './MicrosoftLogo';
export { default as OlaLogo } from './OlaLogo';
export { default as OyoLogo } from './OyoLogo';
export { default as WalmartLogo } from './WalmartLogo';
